### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by 27mfp** [starxg/tabnine-crack#1]
Hello, any instructions on how to use?

**Comment by starxg** [comment]
<img width="217" alt="image" src="https://github.com/starxg/tabnine-crack/assets/34997494/d926415f-562e-4c3d-b0fd-53167d73a58e">

first click `Open Tabnine Hub` then click `Setting` , it's done.

<img width="379" alt="image" src="https://github.com/starxg/tabnine-crack/assets/34997494/7b6f1e74-7a08-43d0-9adc-eae67c50ec65">

**Comment by starxg** [comment]
> what IDE are you using, also does it work on vscode?

My IDE is `IntelliJ IDEA`.

Here is how to use VSCode


1. Click `Help` -> `Toggle Developer Tools` -> `Network`
2. Click `Tabnine`
    <img width="306" alt="image" src="https://github.com/starxg/tabnine-crack/assets/34997494/4e1f1006-056e-4f50-a128-1c5688f288a1">
3. Copy this url    
    <img width="675" alt="image" src="https://github.com/starxg/tabnine-crack/assets/34997494/37e8e63c-fb5e-48f3-99ec-3e68210b8d82">
4. Close this tab
    <img width="292" alt="image" src="https://github.com/starxg/tabnine-crack/assets/34997494/8a27e1cf-94f7-47b3-b2c2-a0689d249ce2">
5. Open the url in the browser `(Your browser must install this plug-in)`
6. Click `Settings` , it's done!
    <img width="1037" alt="image" src="https://github.com/starxg/tabnine-crack/assets/34997494/ee5aa55a-0879-4993-bb42-94df64b2aa6a">
